/**
 * @file    char_lcd.c
 * @brief   HD44780 character LCD, 4-bit / 8-bit parallel (LCD1602 / LCD2004 / LiquidCrystal) - implementation.
 *
 * @author  Khue Nguyen
 * @website khuenguyencreator.com
 * @youtube https://www.youtube.com/channel/UCt8cFnPOaHrQXWmVkk-lfvg
 */
#include "char_lcd.h"


//************************ Low Level Function *****************************************//
static void CHAR_LCD_Delay(uint16_t Time)
{
	HAL_Delay(Time);
	
}
static void CHAR_LCD_Write8(CHAR_LCD_Device* LCD, uint8_t Data, uint8_t Mode)
{
	if(Mode == CHAR_LCD_COMMAND)
	{
		HAL_GPIO_WritePin(LCD->RS_PORT, LCD->RS_PIN, GPIO_PIN_RESET);// RS = 0, write cmd
	}
	else if(Mode == CHAR_LCD_DATA)
	{
		HAL_GPIO_WritePin(LCD->RS_PORT, LCD->RS_PIN, GPIO_PIN_SET);// RS = 1, write data
	}
	HAL_GPIO_WritePin(LCD->D0_PORT, LCD->D0_PIN, Data&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D1_PORT, LCD->D1_PIN, Data>>1&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D2_PORT, LCD->D2_PIN, Data>>2&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D3_PORT, LCD->D3_PIN, Data>>3&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D4_PORT, LCD->D4_PIN, Data>>4&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D5_PORT, LCD->D5_PIN, Data>>5&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D6_PORT, LCD->D6_PIN, Data>>6&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D7_PORT, LCD->D7_PIN, Data>>7&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_RESET);
	CHAR_LCD_Delay(1);
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_SET);
	CHAR_LCD_Delay(1);
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_RESET);
	CHAR_LCD_Delay(1);
}
static void CHAR_LCD_Write4(CHAR_LCD_Device* LCD, uint8_t Data, uint8_t Mode)
{
	uint8_t Data_H = Data >>4;
	uint8_t Data_L = Data;
	if(Mode == CHAR_LCD_COMMAND)
	{
		HAL_GPIO_WritePin(LCD->RS_PORT, LCD->RS_PIN, GPIO_PIN_RESET);// RS = 0, write cmd
	}
	else if(Mode == CHAR_LCD_DATA)
	{
		HAL_GPIO_WritePin(LCD->RS_PORT, LCD->RS_PIN, GPIO_PIN_SET);// RS = 1, write data
	}
	HAL_GPIO_WritePin(LCD->D4_PORT, LCD->D4_PIN, Data_H&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D5_PORT, LCD->D5_PIN, Data_H>>1&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D6_PORT, LCD->D6_PIN, Data_H>>2&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D7_PORT, LCD->D7_PIN, Data_H>>3&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_RESET);
	CHAR_LCD_Delay(1);
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_SET);
	CHAR_LCD_Delay(1);
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_RESET);
	CHAR_LCD_Delay(1);
	
	HAL_GPIO_WritePin(LCD->D4_PORT, LCD->D4_PIN, Data_L&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D5_PORT, LCD->D5_PIN, Data_L>>1&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D6_PORT, LCD->D6_PIN, Data_L>>2&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LCD->D7_PORT, LCD->D7_PIN, Data_L>>3&0x01?GPIO_PIN_SET:GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_RESET);
	CHAR_LCD_Delay(1);
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_SET);
	CHAR_LCD_Delay(1);
	HAL_GPIO_WritePin(LCD->EN_PORT, LCD->EN_PIN, GPIO_PIN_RESET);
	CHAR_LCD_Delay(1);
}
//************************ High Level Function *****************************************//
void CHAR_LCD_8BIT_Init(CHAR_LCD_Device* LCD, uint8_t Colum, uint8_t Row,
									GPIO_TypeDef* RS_PORT, uint16_t RS_PIN, GPIO_TypeDef* EN_PORT, uint16_t EN_PIN,
									GPIO_TypeDef* D0_PORT, uint16_t D0_PIN, GPIO_TypeDef* D1_PORT, uint16_t D1_PIN,
									GPIO_TypeDef* D2_PORT, uint16_t D2_PIN, GPIO_TypeDef* D3_PORT, uint16_t D3_PIN,
									GPIO_TypeDef* D4_PORT, uint16_t D4_PIN, GPIO_TypeDef* D5_PORT, uint16_t D5_PIN,
									GPIO_TypeDef* D6_PORT, uint16_t D6_PIN, GPIO_TypeDef* D7_PORT, uint16_t D7_PIN)
{
	LCD->MODE = LCD_8BITMODE;
	LCD->COLUMS = Colum;
	LCD->ROWS = Row;
	LCD->RS_PORT = RS_PORT;
	LCD->RS_PIN = RS_PIN;
	LCD->EN_PORT = EN_PORT;
	LCD->EN_PIN = EN_PIN;
	LCD->D0_PORT = D0_PORT;
	LCD->D0_PIN = D0_PIN;
	LCD->D1_PORT = D1_PORT;
	LCD->D1_PIN = D1_PIN;
	LCD->D2_PORT = D2_PORT;
	LCD->D2_PIN = D2_PIN;
	LCD->D3_PORT = D3_PORT;
	LCD->D3_PIN = D3_PIN;
	LCD->D4_PORT = D4_PORT;
	LCD->D4_PIN = D4_PIN;
	LCD->D5_PORT = D5_PORT;
	LCD->D5_PIN = D5_PIN;
	LCD->D6_PORT = D6_PORT;
	LCD->D6_PIN = D6_PIN;
	LCD->D7_PORT = D7_PORT;
	LCD->D7_PIN = D7_PIN;
	CHAR_LCD_Delay(50);
	LCD->FUNCTIONSET = LCD_FUNCTIONSET|LCD_8BITMODE|LCD_2LINE|LCD_5x8DOTS;
	LCD->ENTRYMODE = LCD_ENTRYMODESET|LCD_ENTRYLEFT|LCD_ENTRYSHIFTDECREMENT;
	LCD->DISPLAYCTRL = LCD_DISPLAYCONTROL|LCD_DISPLAYON|LCD_CURSOROFF|LCD_BLINKOFF;
	LCD->CURSORSHIFT = LCD_CURSORSHIFT|LCD_CURSORMOVE|LCD_MOVERIGHT;
	
	CHAR_LCD_Write8(LCD, LCD->ENTRYMODE,CHAR_LCD_COMMAND);
	CHAR_LCD_Write8(LCD, LCD->DISPLAYCTRL,CHAR_LCD_COMMAND);
	CHAR_LCD_Write8(LCD, LCD->CURSORSHIFT,CHAR_LCD_COMMAND);
	CHAR_LCD_Write8(LCD, LCD->FUNCTIONSET,CHAR_LCD_COMMAND);
	
	CHAR_LCD_Write8(LCD, LCD_CLEARDISPLAY,CHAR_LCD_COMMAND);
	CHAR_LCD_Write8(LCD, LCD_RETURNHOME,CHAR_LCD_COMMAND);
}

void CHAR_LCD_4BIT_Init(CHAR_LCD_Device* LCD, uint8_t Colum, uint8_t Row,
									GPIO_TypeDef* RS_PORT, uint16_t RS_PIN, GPIO_TypeDef* EN_PORT, uint16_t EN_PIN,
									GPIO_TypeDef* D4_PORT, uint16_t D4_PIN, GPIO_TypeDef* D5_PORT, uint16_t D5_PIN,
									GPIO_TypeDef* D6_PORT, uint16_t D6_PIN, GPIO_TypeDef* D7_PORT, uint16_t D7_PIN)
{
	LCD->MODE = LCD_4BITMODE;
	LCD->COLUMS = Colum;
	LCD->ROWS = Row;
	LCD->RS_PORT = RS_PORT;
	LCD->RS_PIN = RS_PIN;
	LCD->EN_PORT = EN_PORT;
	LCD->EN_PIN = EN_PIN;
	LCD->D4_PORT = D4_PORT;
	LCD->D4_PIN = D4_PIN;
	LCD->D5_PORT = D5_PORT;
	LCD->D5_PIN = D5_PIN;
	LCD->D6_PORT = D6_PORT;
	LCD->D6_PIN = D6_PIN;
	LCD->D7_PORT = D7_PORT;
	LCD->D7_PIN = D7_PIN;
	LCD->FUNCTIONSET = LCD_FUNCTIONSET|LCD_4BITMODE|LCD_2LINE|LCD_5x8DOTS;
	LCD->ENTRYMODE = LCD_ENTRYMODESET|LCD_ENTRYLEFT|LCD_ENTRYSHIFTDECREMENT;
	LCD->DISPLAYCTRL = LCD_DISPLAYCONTROL|LCD_DISPLAYON|LCD_CURSOROFF|LCD_BLINKOFF;
	LCD->CURSORSHIFT = LCD_CURSORSHIFT|LCD_CURSORMOVE|LCD_MOVERIGHT;
	
	CHAR_LCD_Delay(50);
	CHAR_LCD_Write4(LCD, 0x33, CHAR_LCD_COMMAND);
	CHAR_LCD_Delay(5);
	CHAR_LCD_Write4(LCD, 0x33, CHAR_LCD_COMMAND);
	CHAR_LCD_Delay(5);
	CHAR_LCD_Write4(LCD, 0x32, CHAR_LCD_COMMAND);
	CHAR_LCD_Delay(5);
	
	CHAR_LCD_Write4(LCD, LCD->ENTRYMODE,CHAR_LCD_COMMAND);
	CHAR_LCD_Write4(LCD, LCD->DISPLAYCTRL,CHAR_LCD_COMMAND);
	CHAR_LCD_Write4(LCD, LCD->CURSORSHIFT,CHAR_LCD_COMMAND);
	CHAR_LCD_Write4(LCD, LCD->FUNCTIONSET,CHAR_LCD_COMMAND);
	
	CHAR_LCD_Write4(LCD, LCD_CLEARDISPLAY,CHAR_LCD_COMMAND);
	CHAR_LCD_Write4(LCD, LCD_RETURNHOME,CHAR_LCD_COMMAND);
}
void CHAR_LCD_SetCursor(CHAR_LCD_Device* LCD, uint8_t Xpos, uint8_t Ypos)
{
	
	uint8_t DRAM_ADDRESS = 0x00;
	uint8_t DRAM_OFFSET[4] = {0x00, 0x40, 0x14, 0x54};
	if(Xpos >= LCD->COLUMS)
	{
		Xpos = LCD->COLUMS - 1;
	}
	if(Ypos >= LCD->ROWS)
	{
		Ypos = LCD->ROWS -1;
	}
	DRAM_ADDRESS = DRAM_OFFSET[Ypos] + Xpos;
	if(LCD->MODE == LCD_8BITMODE)
	{
		CHAR_LCD_Write8(LCD, LCD_SETDDRAMADDR|DRAM_ADDRESS, CHAR_LCD_COMMAND);
	}
	else if(LCD->MODE == LCD_4BITMODE)
	{
		CHAR_LCD_Write4(LCD, LCD_SETDDRAMADDR|DRAM_ADDRESS, CHAR_LCD_COMMAND);
	}
}
void CHAR_LCD_WriteChar(CHAR_LCD_Device* LCD, char character)
{
	if(LCD->MODE == LCD_8BITMODE)
	{
		CHAR_LCD_Write8(LCD, character, CHAR_LCD_DATA);
	}
	else if(LCD->MODE == LCD_4BITMODE)
	{
		CHAR_LCD_Write4(LCD, character, CHAR_LCD_DATA);
	}
}
void CHAR_LCD_WriteString(CHAR_LCD_Device* LCD, char *String)
{
	while(*String)CHAR_LCD_WriteChar(LCD, *String++);
}
void CHAR_LCD_Clear(CHAR_LCD_Device* LCD)
{
	if(LCD->MODE == LCD_8BITMODE)
	{
		CHAR_LCD_Write8(LCD, LCD_CLEARDISPLAY, CHAR_LCD_COMMAND);
	}
	else if(LCD->MODE == LCD_4BITMODE)
	{
		CHAR_LCD_Write4(LCD, LCD_CLEARDISPLAY, CHAR_LCD_COMMAND);
	}
	CHAR_LCD_Delay(5);
}
void CHAR_LCD_ReturnHome(CHAR_LCD_Device* LCD)
{
	if(LCD->MODE == LCD_8BITMODE)
	{
		CHAR_LCD_Write8(LCD, LCD_RETURNHOME, CHAR_LCD_COMMAND);
	}
	else if(LCD->MODE == LCD_4BITMODE)
	{
		CHAR_LCD_Write4(LCD, LCD_RETURNHOME, CHAR_LCD_COMMAND);
	}
	CHAR_LCD_Delay(5);
}
void CHAR_LCD_CursorOn(CHAR_LCD_Device* LCD)
{
	LCD->DISPLAYCTRL |= LCD_CURSORON;
	if(LCD->MODE == LCD_8BITMODE)
	{
		CHAR_LCD_Write8(LCD, LCD->DISPLAYCTRL, CHAR_LCD_COMMAND);
	}
	else if(LCD->MODE == LCD_4BITMODE)
	{
		CHAR_LCD_Write4(LCD, LCD->DISPLAYCTRL, CHAR_LCD_COMMAND);
	}
}
void CHAR_LCD_CursorOff(CHAR_LCD_Device* LCD)
{
	LCD->DISPLAYCTRL &= ~LCD_CURSORON;
	if(LCD->MODE == LCD_8BITMODE)
	{
		CHAR_LCD_Write8(LCD, LCD->DISPLAYCTRL, CHAR_LCD_COMMAND);
	}
	else if(LCD->MODE == LCD_4BITMODE)
	{
		CHAR_LCD_Write4(LCD, LCD->DISPLAYCTRL, CHAR_LCD_COMMAND);
	}
}
void CHAR_LCD_BlinkOn(CHAR_LCD_Device* LCD)
{
	LCD->DISPLAYCTRL |= LCD_BLINKON;
	if(LCD->MODE == LCD_8BITMODE)
	{
		CHAR_LCD_Write8(LCD, LCD->DISPLAYCTRL, CHAR_LCD_COMMAND);
	}
	else if(LCD->MODE == LCD_4BITMODE)
	{
		CHAR_LCD_Write4(LCD, LCD->DISPLAYCTRL, CHAR_LCD_COMMAND);
	}
}
void CHAR_LCD_BlinkOff(CHAR_LCD_Device* LCD)
{
	LCD->DISPLAYCTRL &= ~LCD_BLINKON;
	if(LCD->MODE == LCD_8BITMODE)
	{
		CHAR_LCD_Write8(LCD, LCD->DISPLAYCTRL, CHAR_LCD_COMMAND);
	}
	else if(LCD->MODE == LCD_4BITMODE)
	{
		CHAR_LCD_Write4(LCD, LCD->DISPLAYCTRL, CHAR_LCD_COMMAND);
	}
	
}
